### PR TITLE
refactor(webapp): page layout

### PR DESCRIPTION
**Pull request by GabenGar**
Lots of things:
- sticky footer
- redone account nav button
- all pages share the same layout component (and therefore global state between client transitions)

### CODE REVIEW

**Comment by horahoradev** [comment]
for future large prs: please include link to a cute video as a bribe

otherwise: LGTM! this is quite a lot of work, thank you!

**Comment by GabenGar** [comment]
It isn't really possible to have a small PR which affects every single page.

[SNH48《光之轨迹》MV](https://www.youtube.com/watch?v=_50OL6bujXc)

Also wait a sec with merging, the webapp doesn't build with the account context present. I'll ping you up when it gets resolved.

**Comment by GabenGar** [comment]
@horahoradev 
Okay it's ready to merge.

**Comment by horahoradev** [comment]
Thanks, merged! I accept your bribe

**Pull request merged**
