### PR TITLE
feat: json schema prep

### PR DESCRIPTION
**Pull request by GabenGar**
For now added a schema for all environment variables mentioned in `secrets.env.template` and `docker-compose.yml.envs`.

### CODE REVIEW

**Comment by horahoradev** [comment]
What's the value proposition over envsubst?

**Comment by GabenGar** [comment]
1. Not having a situation like this:
    ```sh
    docker ps --all
    ```
    envsubst-cintainer-spam
2. Not relying on some unix util with questionable format for basic env var management.
3. More like what is the point of having `envsubst` in the first place? As far as I understood it's used to juggle env vars around to interpolate them into the final `docker-compose.yml` config. Except config can [interpolate env vars by itself](https://docs.docker.com/compose/environment-variables/)
 and the file with env vars [can be passed as an option](https://docs.docker.com/compose/env-file/).
4. Better documentation obviously.
5. It's not for env vars only, json schema can validate any format which can be serialized as json. Configs being a collection of key/value pairs which has to be passed around (aka being serializable) fits the bill, although env vars have to be validated with less strict rulesets than usual jsons due to basically being `map[string]string`.
6. The main use-case is validating client inputs in API and making sure both client and server validate them the same way.

**Comment by horahoradev** [comment]
1. We could get rid of that situation without a radical redesign
2. sure, but how would we make it better?
3. it generates a template for docker-compose out of the provided secrets
4. How does json schema accomplish this?
6. services will crash if they aren't configured in the right way (they'll just panic if they don't have a required env var). Does this streamline the configuration process for users?

**Comment by GabenGar** [comment]
1. Yeah we could get rid of the situation by getting rid of this `envsubst` step. One less implicit dependency and less steps to start the stack.
2. You really asking how storing all env vars used by the project in a single place in a serializable format understandable by every single programming language in existence (I guess pre-C languages can't into json) is better than just spreading them across several files implicitly with a bash script? Again, how do you validate the problems with env vars in the current setup, beyond just crashing it somewhere in runtime and hoping the error is more descriptive than just `error: value is nil`?
3. There is no reason to have this template generation step in the first place. Again, the config can interpolate values directly from environment so it can be checked in the repo while also being customizable through the `.env` file, the default values for which can be generated from the schema (and updated with new keys semi-automatically later one).
4. Quite literally, it has various [annotation fields](https://json-schema.org/understanding-json-schema/reference/generic.html#id2), `description` specifically, which has to be written in human-readable form and then can be used for doc generation.
5. It streamlines quite a lot, since you can just run configuration validation at the start of the program and crash it with helpful error messages before even doing any runtime logic. Or do it in a separate step, before reving up any docker containers.

**Comment by horahoradev** [comment]
ok, earlier validation and documentation is good. if we could get e.g. regex for each value (where relevant), that would be helpful.

**Pull request merged**
