### PR TITLE
refactor(webapp): archive requests page

### PR DESCRIPTION
**Pull request by GabenGar**
Split `/account/archive-requests` into 4 pages:
- `/account/archives` - Root page with links to the others.
- `/account/archives/requests` - Requests page.
- `/account/archives/events` - Events page.
- `/account/archives/downloads` - Downloads page.

### CODE REVIEW

**Comment by horahoradev** [comment]
I don't disagree with the need for refactoring... but four pages? let me check this out

**Comment by horahoradev** [comment]
ok yeah, it's as the PR says: we have three separate pages now.
I think it's helpful to have everything on one page as a dashboard.
Maybe we could refactor into three components, but keep them all on the same page?

**Comment by GabenGar** [comment]
It's not helpful because it's not mobile-friendly. Basically anything wider than 360px or a table layout is not mobile-friendly. That also means all figma design mocks are not mobile-friendly either.
Maybe later on it will have a tab switch between the 3 on the page (or even show all 3 of them at once for higher resolutions), but that requires refactoring the whole general page layout, so out of scope for this PR. But the main reason for separation is to untangle the mess which is the code for this page. I was really surprised all that websocket setup was used only for the download progress part, that fact you can't pick up on until the page is properly decomposed into parts.

**Comment by horahoradev** [comment]
shit we're mobile friendly now?
couldn't we just have them all in a flexbox such that they'd be in one column on mobile?
we'll just have to do something a little more user friendly before we do a new release onto master

**Comment by GabenGar** [comment]
We aren't mobile, but more adaptive than before. And it's pretty hard to do an adaptive design with the desktop as base than a mobile base. And putting them into one flexbox container is not a solution since it's a lotta scrolling to get to one section (and requires rewriting tables into the card lists anyway).

**Pull request merged**
